config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :achievements
  root 'welcome#index'
end

app/models/achievement.rb
class Achievement < ApplicationRecord
  belongs_to :user
  validates :title, presence: true
  validates :user, presence: true
  validates :title, uniqueness: {
    scope: :user_id,
    message: "you can't have two achievements with the same title"
  }
  enum privacy: { public_access: 0, private_access: 1, friends_access: 2 }

  def description_html
    Redcarpet::Markdown.new(Redcarpet::Render::HTML).render(description)
  end

  def silly_title
    "#{title} by #{user.email}"
  end

  def self.by_letter(letter)
    includes(:user).where('title LIKE ?', "#{letter}%").order('users.email')
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
  has_many :achievements
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/achievements_controller.rb
class AchievementsController < ApplicationController
  before_action :authenticate_user!, only: %i[new edit create update destroy]
  before_action :owners_only, only: %i[edit update destroy]
  def new
    @achievement = Achievement.new
  end

  def index
    @achievements = Achievement.public_access
  end

  def show
    @achievement = Achievement.find(params[:id])
  end

  def edit; end

  def update
    if @achievement.update(achievement_params)
      redirect_to(achievement_path(params[:id]))
    else
      render :edit
    end
  end

  def create
    @achievement = current_user.achievements.new(achievement_params)
    if @achievement.save
      redirect_to achievement_path(@achievement), notice: 'Achievement has been created'
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @achievement.destroy
    redirect_to achievements_path
  end

  private

  def achievement_params
    params.require(:achievement).permit(:title, :description, :privacy, :cover_image, :featured, :user_id)
  end

  def owners_only
    @achievement = Achievement.find(params[:id])
    return unless current_user != @achievement.user

    redirect_to achievements_path
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    request.variant = :without_turbo_stream if request.headers['Turbo-Frame'].nil?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/form_helper.rb
module FormHelper
  def errors_for(form, field)
    content_tag(:p, form.object.errors[field].try(:first), class: 'help-block')
  end

  def form_group_for(form, field, opts = {}, &block)
    label = opts.fetch(:label) { true }
    has_errors = form.object.errors[field].present?

    content_tag :div, class: "form-group #{'has-error' if has_errors}" do
      concat form.label(field, class: 'control-label') if label
      concat capture(&block)
      concat errors_for(form, field)
    end
  end
end

app/views/achievements/_form.html.erb
<%= simple_form_for @achievement, html: { class: 'form',data: { turbo: false } } do |f| %>
  <div class="mb-3">
    <%= f.input :title , input_html: { class: 'form-control' } %>
  </div>
  <div class="mb-3">
    <%= f.input :description, label: 'Description' , as: :text, input_html: { class:'form-control' } %>
  </div>
  <div class="mb-3">
    <%= f.input :privacy, collection: Achievement.privacies.map { |key, value| [key.humanize.split.first, key] }, include_blank: 'Privacy' ,
      label: 'Privacy' , input_html: { class: 'form-select' } %>
  </div>
  <div class="mb-3 form-check">
    <%= f.input :featured, as: :boolean, label: 'Featured achievement' , input_html: { class: 'form-check-input' } %>
  </div>
  <div class="mb-3">
    <%= f.input :cover_image, as: :file, label: 'Cover image' ,input_html: { class: 'form-control-file mb-3' } %>
  </div>
  <div class="mb-3 actions">
    <%= f.submit class: 'btn btn-primary' %>
  </div>
  <% end %>

app/views/achievements/new.html.erb
<div class="container">
  <div class="row">
    
    <div class="col-md-6 offset-md-3">
      <h1 class="text-center">Nuevo Registro</h1>
      <%= turbo_frame_tag 'new_achievement_form' do %>
        <%= render 'form', achievement: @achievement %>
      <% end %>
    </div>
  </div>
</div

app/views/achievements/show.html.erb
<h1><%=@achievement.title%></h1>
<div><%=@achievement.description_html.html_safe %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RockyApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-lg bg-body-tertiary">
      <div class="container-fluid">
        <a class="navbar-brand" href="#">Navbar</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <%= link_to 'New Achievement', new_achievement_path %>
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <% if flash[:notice] %>
      <div class="alert alert-info">
        <%= flash[:notice] %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Welcome</h1>